[package]
name = "ytrs"
version = "0.1.0"
authors = ["Avarel <avarelpm@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.17"
hyper = "0.12"
url = "1.7.2"
tokio = "0.1.18"
tokio-tls = "0.2.1"
native-tls = "0.2"
error-chain = "0.12.0"